<?php if ($block->getPaymentMethodTitle() == 'CA Raty') : ?>
    <?php
    $formData = $block->getOrderData();
    $helper = $this->helper("CA\CARaty\Helper\Data");
    ?>
    <br>
    <h3>Płatność CA Raty</h3>
    <p><b>Proszę przejść do wniosku klikając poniższy przycisk.</b></p>
    <br>
    <form method="POST" id="caraty-form" action="https://ewniosek.credit-agricole.pl/eWniosek/simulator_u.jsp">
        <input
            alt="Wypełnij formularz"
            id="caraty_submit"
            src="<?= $helper->getConfig('payment/ca_raty/button_send_url'); ?>"
            type="image"
            value="Potwierdzam zamówienie"
        />
        <input type="hidden" name="PARAM_TYPE" value="RAT"/>
        <input type="hidden" name="PARAM_PROFILE" value="<?= $formData['PARAM_PROFILE'] ?>"/>
        <input type="hidden" name="POST_ATTR" value="1"/>
        <input type="hidden" name="email.address" value="<?= $formData['email'] ?>"/>
        <input type="hidden" name="cart.orderNumber" value="<?= $formData['orderNumber'] ?>"/>
        <input type="hidden" name="PARAM_CREDIT_AMOUNT" value="<?= $formData['PARAM_CREDIT_AMOUNT'] ?>"/>
        <input type="hidden" name="PARAM_AUTH" value="2"/>
        <input type="hidden" name="PARAM_HASH" value="<?= $formData['PARAM_HASH'] ?>"/>
        <input type="hidden" name="randomizer" value="<?= $formData['randomizer'] ?>"/>
        <?php $index = 1; ?>
        <?php foreach ($formData['items'] as $item) : ?>
        <input type="hidden" name="<?= "cart.itemName" . $index ?>" value="<?= htmlentities($item['name'], ENT_QUOTES, "UTF-8") ?>"/>
        <input type="hidden" name="<?= "cart.itemQty" . $index ?>" value="<?= $item['qty'] ?>"/>
        <input type="hidden" name="<?= "cart.itemPrice" . $index ?>" value="<?= $item['price'] ?>"/>
            <?php $index++; ?>
        <?php endforeach; ?>
        <?php if ($helper->isAutoButton() === true) : $offerId = $helper->getOrderOfferId($formData['items'], true);?>
        <input type="hidden" name="offerId" value="<?= $offerId ?>"/>
        <?php endif; ?>
    </form>
    <br>
<?php endif; ?>
