<?php
$helper = $this->helper("CA\CARaty\Helper\Data");
$excluded = false;
$items = $this->getQuote()->getAllItems();
foreach ($items as $item) {
    if ($helper->isExcluded($item->getProduct()->getCategoryIds())) {
        $excluded = true;
        break;
    }
}

if (
    $helper->getConfig('payment/ca_raty/active') == 1
    && $helper->getConfig('payment/ca_raty/visibility_cart') != 'disabled'
    && $this->getTotals()['grand_total']->getValue() > $helper->getConfig('payment/ca_raty/min_cart_value')
    && $excluded === false
) : ?>
    <div id="caraty_simulator">
        <script type="text/javascript">
            var ca_raty_total =  <?php echo number_format($this->getTotals()['grand_total']->getValue(), 2, '.', ''); ?>;

            function reformatPrice() {
                let price = jQuery('.grand td').find('span.price');
                if (price.length === 0) {
                    return ca_raty_total;
                }

                return parseFloat(price.text().replace(',', '.').replace(/\s+/g, '').replace(/([a-zA-Z])/g, "")).toFixed(2);
            }

            function PoliczRateCA(args) {
                let total;
                if (typeof args !== 'undefined') {
                    if (typeof args === 'number') {
                        total = args;
                    }
                }
                if (typeof total === 'undefined') {
                    let currentPrice = reformatPrice();
                    if (currentPrice !== 0) {
                        total = currentPrice;
                    }
                }

            <?php if ($helper->isAutoButton() === true) : $offerId = $helper->getCartOfferId($items); ?>
                var offerId = '<?php echo $offerId;?>';
                window.open('https://ewniosek.credit-agricole.pl/eWniosek/simulator.jsp?PARAM_TYPE=RAT&PARAM_PROFILE=<?php echo $helper->getConfig('payment/ca_raty/psp_id'); ?>&PARAM_CREDIT_AMOUNT=' + total + '&offerId=' + offerId, 'Policz_rate');
            <?php else: ?>
                window.open('https://ewniosek.credit-agricole.pl/eWniosek/simulator.jsp?PARAM_TYPE=RAT&PARAM_PROFILE=<?php echo $helper->getConfig('payment/ca_raty/psp_id'); ?>&PARAM_CREDIT_AMOUNT=' + total, 'Policz_rate');
            <?php endif; ?>
        }
        </script>
        <?php if ($helper->getConfig('payment/ca_raty/visibility_cart') != 'hidden') : ?>
            <p align="center" class="buttons_bottom_block">
                <?php if ($helper->isAutoButton() === true) : ?>
                    <a onclick="PoliczRateCA();" style="cursor: pointer;" target="raty_symulator" title="Kupuj na Raty!">
                        <img alt="" src="<?php echo $helper->getAutoButtonUrl($this->getTotals()['grand_total']->getValue(), $offerId); ?>">
                    </a>
                <?php else : ?>
                    <a onclick="PoliczRateCA();" style="cursor: pointer;" target="raty_symulator" title="Kupuj na Raty!">
                        <img alt="" src="<?php echo $helper->getConfig('payment/ca_raty/button_simulator_url'); ?>">
                    </a>
                <?php endif; ?>
            </p>
        <?php endif; ?>
    </div>
<?php endif; ?>
